server:
  port: 9087
  servlet:
    context-path: /api/users-management

health:
  config:
    enabled: false




# ===============================
# = DATABASE STUFF
# ===============================
spring:
  application:
    name: users
    cloud:
      config:
        enabled: true
        failFast: true
        label: master
        discovery:
          enabled: true
          serviceId: configserver
  jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/bdentuisjc
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update

  logging:
    level:
      org.hibernate: DEBUG
      org.hibernate.SQL: DEBUG

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:5000}/eureka/
#      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8080}/discovery/eureka
# ===============================
# = Key to sign jwt tokens
# ===============================
signing:
  key: hufkhjbdszp$$kl$@jhjkhkkk
